package com.huawei.hms.adapter.analytics.utils

import com.google.firebase.analytics.FirebaseAnalytics
import com.google.firebase.analytics.FirebaseAnalytics.Event.*
import com.google.firebase.analytics.FirebaseAnalytics.Param.SCORE
import com.huawei.hms.analytics.type.HAEventType.*

val GMS2HMSEvents = mapOf(
    ADD_PAYMENT_INFO to CREATEPAYMENTINFO,
    ADD_TO_CART to ADDPRODUCT2CART,
    ADD_TO_WISHLIST to ADDPRODUCT2WISHLIST,

    APP_OPEN to APP_OPEN,

    LEVEL_START to STARTLEVEL,
    LEVEL_END to COMPLETELEVEL,
    LEVEL_UP to UPGRADELEVEL,
    UNLOCK_ACHIEVEMENT to OBTAINACHIEVEMENT,
    POST_SCORE to SUBMITSCORE,

    EARN_VIRTUAL_CURRENCY to WINVIRTUALCOIN,
    SPEND_VIRTUAL_CURRENCY to CONSUMEVIRTUALCOIN,

    LOGIN to SIGNIN,
    SIGN_UP to REGISTERACCOUNT,
    SHARE to SHARECONTENT,
    JOIN_GROUP to JOINUSERGROUP,

    BEGIN_CHECKOUT to STARTCHECKOUT,
    CAMPAIGN_DETAILS to CAMPAIGN_DETAILS,
    GENERATE_LEAD to OBTAINLEADS,
    REMOVE_FROM_CART to DELPRODUCTFROMCART,


    TUTORIAL_BEGIN to STARTTUTORIAL,
    TUTORIAL_COMPLETE to COMPLETETUTORIAL,

    VIEW_ITEM to VIEWPRODUCT,
    VIEW_ITEM_LIST to VIEWPRODUCTLIST,
    VIEW_SEARCH_RESULTS to VIEWSEARCHRESULT,

    FirebaseAnalytics.Event.SEARCH to com.huawei.hms.analytics.type.HAEventType.SEARCH
)

val GMS2HMSParams = mapOf(
    SCORE to com.huawei.hms.analytics.type.HAParamType.SCORE
)

val HmsEventsList = setOf(
    CREATEPAYMENTINFO,
    ADDPRODUCT2CART,
    ADDPRODUCT2WISHLIST,
    STARTAPP,
    STARTCHECKOUT,
    VIEWCAMPAIGN,
    VIEWCHECKOUTSTEP,
    WINVIRTUALCOIN,
    COMPLETEPURCHASE,
    OBTAINLEADS,
    JOINUSERGROUP,
    COMPLETELEVEL,
    STARTLEVEL,
    UPGRADELEVEL,
    SIGNIN,
    SIGNOUT,
    SUBMITSCORE,
    CREATEORDER,
    REFUNDORDER,
    DELPRODUCTFROMCART,
    com.huawei.hms.analytics.type.HAEventType.SEARCH,
    VIEWCONTENT,
    UPDATECHECKOUTOPTION,
    SHARECONTENT,
    REGISTERACCOUNT,
    CONSUMEVIRTUALCOIN,
    STARTTUTORIAL,
    COMPLETETUTORIAL,
    OBTAINACHIEVEMENT,
    VIEWPRODUCT,
    VIEWPRODUCTLIST,
    VIEWSEARCHRESULT,
    UPDATEMEMBERSHIPLEVEL,
    FILTRATEPRODUCT,
    VIEWCATEGORY,
    UPDATEORDER,
    CANCELORDER,
    COMPLETEORDER,
    CANCELCHECKOUT,
    OBTAINVOUCHER,
    CONTACTCUSTOMSERVICE,
    RATE,
    INVITE
)